/**
 * Renders Chrome Web Store / AMO listing screenshots for VideoSpeeds.
 *
 * Produces five 1280x800 JPEGs (the CWS-required format — exactly that
 * resolution, no alpha channel):
 *   01-youtube-panel.jpg   — full mock YouTube watch page with the panel
 *   02-youtube-settings.jpg — same page with the settings modal open
 *   03-rutube-panel.jpg    — full mock RuTube watch page with the panel
 *   04-rutube-settings.jpg — same page with the settings modal open
 *   05-welcome-page.jpg    — extension's actual welcome.html
 *
 * Why a mock page rather than a live youtube.com / rutube.ru visit:
 *   - Living sites are reachable from very few headless setups (consent
 *     walls, anti-bot, login walls, regional blocks). A mock renders
 *     identically every run and can be regenerated by anyone who clones
 *     the repo.
 *   - The mock uses VERBATIM CSS from src/ui/styles.ts (copy-pasted
 *     into each mock HTML), so the panel reads exactly as the user sees
 *     it on a real installation. Only the host-page chrome (masthead,
 *     player gradient, video metadata) is synthetic.
 *
 * Welcome is rendered through the actual built extension (loaded as
 * unpacked), so it ships with all live JS modules and CSS.
 *
 * deviceScaleFactor stays at 1 — Chrome Web Store requires the screenshot
 * dimensions to match EXACTLY 1280x800 (or 640x400). With DPR=2 the
 * output PNG was 2560x1600 and CWS rejected it as "image size incorrect".
 *
 * Output format is JPEG to satisfy CWS's "JPEG or 24-bit PNG (no alpha)"
 * rule with no extra post-processing.
 */

import { chromium } from '@playwright/test';
import { mkdirSync, existsSync, readdirSync, unlinkSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..', '..');
const OUT = resolve(REPO, 'dist-store-assets', 'screenshots');
const MOCK_YT = resolve(__dirname, 'mock-youtube.html');
const MOCK_RT = resolve(__dirname, 'mock-rutube.html');
const EXT_DIR = resolve(REPO, '.output', 'chrome-mv3');

if (!existsSync(EXT_DIR)) {
  console.error(`Extension build missing: ${EXT_DIR}\nRun \`npm run build\` first.`);
  process.exit(1);
}

if (!existsSync(OUT)) {
  mkdirSync(OUT, { recursive: true });
} else {
  for (const f of readdirSync(OUT)) {
    if (/\.(png|jpe?g)$/i.test(f)) unlinkSync(join(OUT, f));
  }
  console.log(`cleaned ${OUT}`);
}

const userDataDir = resolve(__dirname, '.tmp-profile');
const ctx = await chromium.launchPersistentContext(userDataDir, {
  headless: false,
  args: [
    `--disable-extensions-except=${EXT_DIR}`,
    `--load-extension=${EXT_DIR}`,
    '--no-first-run',
    '--no-default-browser-check',
  ],
  viewport: { width: 1280, height: 800 },
  deviceScaleFactor: 1,
});

let n = 1;
async function shoot(page, name) {
  const file = join(OUT, `${String(n).padStart(2, '0')}-${name}.jpg`);
  await page.screenshot({ path: file, type: 'jpeg', quality: 92 });
  console.log(`saved ${file}`);
  n++;
}

async function shootMock(url, name) {
  const page = await ctx.newPage();
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.goto(url, { waitUntil: 'load' });
  await page.waitForTimeout(500);
  await shoot(page, name);
}

// 1-2. YouTube mock — panel only, then settings modal open.
await shootMock(pathToFileURL(MOCK_YT).href, 'youtube-panel');
await shootMock(pathToFileURL(MOCK_YT).href + '?modal=1', 'youtube-settings');

// 3-4. RuTube mock — panel only, then settings modal open.
await shootMock(pathToFileURL(MOCK_RT).href, 'rutube-panel');
await shootMock(pathToFileURL(MOCK_RT).href + '?modal=1', 'rutube-settings');

// 5. Welcome — through the built extension.
let extId = null;
for (let i = 0; i < 30 && !extId; i++) {
  const sw = ctx.serviceWorkers().find((w) => w.url().startsWith('chrome-extension://'));
  if (sw) {
    extId = new URL(sw.url()).host;
    break;
  }
  await new Promise((r) => setTimeout(r, 200));
}

if (extId) {
  const page = await ctx.newPage();
  await page.setViewportSize({ width: 1280, height: 800 });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto(`chrome-extension://${extId}/welcome.html`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1500);
  await shoot(page, 'welcome-page');
} else {
  console.warn('welcome-page skipped: extension service worker not found');
}

await ctx.close();

try {
  const { rmSync } = await import('node:fs');
  rmSync(userDataDir, { recursive: true, force: true });
} catch { /* swallow */ }

console.log(`\nAll screenshots in ${OUT}`);
